name: Publish
on:
  workflow_run:
    workflows: ["pages-build-deploy"]
    branches: [main]
    types: 
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Fetch RSS Data
        id: rss
        uses: CodingBull-dev/newest-rss-post-action@main
        with:
          rss: "https://sequr.be/blog/index.xml"
      - name: Ping Webmention
        run: |
          curl -X POST "https://webmention.app/check?token=${{ secrets.WEBMENTION_APP }}&url=${{ steps.rss.outputs.url }}"
